version: "3.9"
services:
  mongo:
    image: mongo:7.0
    container_name: insigh-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: insigh_user
      MONGO_INITDB_ROOT_PASSWORD: insigh_pass
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
    driver: local
